# Generated by Django 4.2 on 2023-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
