# Generated by Django 4.2 on 2023-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='gasStationLat',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='gasStationLong',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
