# Generated by Django 4.2 on 2023-05-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelApi', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='username',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='GasStation',
        ),
    ]
