# Generated by Django 4.2 on 2023-05-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuelApi', '0005_remove_gasstation_username_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('gasStationID', models.IntegerField(primary_key=True, serialize=False)),
                ('gasStationLat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('gasStationLong', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fuelCompID', models.IntegerField()),
                ('fuelCompNormalName', models.CharField(max_length=45)),
                ('gasStationOwner', models.CharField(max_length=128)),
                ('ddID', models.CharField(max_length=10)),
                ('ddNormalName', models.CharField(max_length=45)),
                ('municipalityID', models.CharField(max_length=10)),
                ('municipalityNormalName', models.CharField(max_length=45)),
                ('countyID', models.CharField(max_length=10)),
                ('countyName', models.CharField(max_length=64)),
                ('gasStationAddress', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=22)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('productID', models.IntegerField(primary_key=True, serialize=False)),
                ('fuelTypeID', models.IntegerField()),
                ('fuelSubTypeID', models.IntegerField()),
                ('fuelNormalName', models.CharField(max_length=64)),
                ('fuelName', models.CharField(max_length=128)),
                ('fuelPrice', models.DecimalField(decimal_places=3, max_digits=4)),
                ('dataUpdated', models.DateTimeField(auto_now=True)),
                ('isPremium', models.BooleanField(default='False')),
                ('gasStationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelApi.gasstation')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelApi.pricedata')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelApi.user')),
            ],
        ),
        migrations.AddField(
            model_name='gasstation',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelApi.user'),
        ),
    ]
