# Generated by Django 4.2 on 2023-05-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelApi', '0008_alter_gasstation_gasstationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='fuelCompNormalName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='gasStationAddress',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='gasStationID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='gasStationOwner',
            field=models.CharField(max_length=255),
        ),
    ]
