# Generated by Django 4.2 on 2023-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelApi', '0010_alter_gasstation_municipalityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='phone1',
            field=models.CharField(max_length=15),
        ),
    ]
