# Generated by Django 4.2 on 2023-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelApi', '0012_alter_gasstation_countyid_alter_gasstation_ddid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasstation',
            name='countyID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='ddID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='phone1',
            field=models.CharField(max_length=40),
        ),
    ]
